create_clock -period 10.000 -name wbClk [get_ports wbClk]
create_clock -period 5.000 -name bftClk [get_ports bftClk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets bftClk]
set_false_path -from [get_clocks wbClk] -to [get_clocks bftClk]
set_false_path -from [get_clocks bftClk] -to [get_clocks wbClk]
set_property IOSTANDARD LVCMOS33 [all_inputs]
set_property IOSTANDARD LVCMOS33 [all_outputs]



set_property PACKAGE_PIN H15 [get_ports bftClk]
set_property PACKAGE_PIN H16 [get_ports wbClk]
set_property PACKAGE_PIN T12 [get_ports {wbOutputData[0]}]
set_property PACKAGE_PIN U13 [get_ports {wbOutputData[2]}]
set_property PACKAGE_PIN W13 [get_ports {wbOutputData[3]}]
set_property PACKAGE_PIN T14 [get_ports {wbOutputData[6]}]
set_property PACKAGE_PIN R14 [get_ports {wbOutputData[7]}]
set_property PACKAGE_PIN P14 [get_ports {wbOutputData[8]}]
set_property PACKAGE_PIN Y17 [get_ports {wbOutputData[9]}]
set_property PACKAGE_PIN W20 [get_ports {wbOutputData[27]}]
set_property PACKAGE_PIN T15 [get_ports {wbOutputData[5]}]
set_property PACKAGE_PIN Y19 [get_ports {wbOutputData[29]}]
set_property PACKAGE_PIN N20 [get_ports {wbOutputData[24]}]
set_property PACKAGE_PIN U14 [get_ports {wbOutputData[18]}]
set_property PACKAGE_PIN U20 [get_ports {wbOutputData[25]}]
set_property PACKAGE_PIN N18 [get_ports {wbOutputData[22]}]
set_property PACKAGE_PIN Y14 [get_ports {wbOutputData[11]}]
set_property PACKAGE_PIN V12 [get_ports {wbOutputData[4]}]
set_property PACKAGE_PIN P20 [get_ports {wbOutputData[23]}]
set_property PACKAGE_PIN T20 [get_ports {wbOutputData[26]}]
set_property PACKAGE_PIN U15 [get_ports {wbOutputData[17]}]
set_property PACKAGE_PIN U18 [get_ports {wbOutputData[20]}]
set_property PACKAGE_PIN V20 [get_ports {wbOutputData[28]}]
set_property PACKAGE_PIN P19 [get_ports {wbOutputData[21]}]
set_property PACKAGE_PIN U19 [get_ports {wbOutputData[19]}]
set_property PACKAGE_PIN W16 [get_ports {wbOutputData[31]}]
set_property PACKAGE_PIN V15 [get_ports {wbOutputData[16]}]
set_property PACKAGE_PIN U17 [get_ports {wbOutputData[13]}]
set_property PACKAGE_PIN V13 [get_ports {wbOutputData[1]}]
set_property PACKAGE_PIN Y18 [get_ports {wbOutputData[30]}]
set_property PACKAGE_PIN W15 [get_ports {wbOutputData[15]}]
set_property PACKAGE_PIN W14 [get_ports {wbOutputData[12]}]
set_property PACKAGE_PIN T16 [get_ports {wbOutputData[14]}]
set_property PACKAGE_PIN Y16 [get_ports {wbOutputData[10]}]
set_property PACKAGE_PIN T19 [get_ports {wbInputData[14]}]
set_property PACKAGE_PIN P16 [get_ports {wbInputData[15]}]
set_property PACKAGE_PIN P15 [get_ports {wbInputData[16]}]
set_property PACKAGE_PIN P18 [get_ports {wbInputData[17]}]
set_property PACKAGE_PIN N17 [get_ports {wbInputData[18]}]
set_property PACKAGE_PIN W19 [get_ports {wbInputData[19]}]
set_property PACKAGE_PIN U12 [get_ports {wbInputData[21]}]
set_property PACKAGE_PIN R18 [get_ports {wbInputData[28]}]
set_property PACKAGE_PIN V18 [get_ports {wbInputData[30]}]
set_property PACKAGE_PIN R16 [get_ports {wbInputData[27]}]
set_property PACKAGE_PIN V16 [get_ports {wbInputData[25]}]
set_property PACKAGE_PIN V17 [get_ports {wbInputData[31]}]
set_property PACKAGE_PIN R19 [get_ports {wbInputData[24]}]
set_property PACKAGE_PIN R17 [get_ports {wbInputData[26]}]
set_property PACKAGE_PIN T17 [get_ports {wbInputData[29]}]
set_property PACKAGE_PIN T10 [get_ports {wbInputData[22]}]
set_property PACKAGE_PIN W18 [get_ports {wbInputData[20]}]
set_property PACKAGE_PIN T11 [get_ports {wbInputData[23]}]
set_property PACKAGE_PIN G17 [get_ports {wbInputData[3]}]
set_property PACKAGE_PIN N15 [get_ports {wbInputData[13]}]
set_property PACKAGE_PIN F20 [get_ports {wbInputData[0]}]
set_property PACKAGE_PIN K14 [get_ports {wbInputData[11]}]
set_property PACKAGE_PIN G18 [get_ports {wbInputData[2]}]
set_property PACKAGE_PIN J14 [get_ports {wbInputData[10]}]
set_property PACKAGE_PIN N16 [get_ports {wbInputData[12]}]
set_property PACKAGE_PIN F19 [get_ports {wbInputData[1]}]
set_property PACKAGE_PIN G15 [get_ports {wbInputData[8]}]
set_property PACKAGE_PIN G19 [get_ports {wbInputData[7]}]
set_property PACKAGE_PIN G20 [get_ports {wbInputData[6]}]
set_property PACKAGE_PIN J20 [get_ports {wbInputData[5]}]
set_property PACKAGE_PIN H20 [get_ports {wbInputData[4]}]
set_property PACKAGE_PIN F16 [get_ports error]
set_property PACKAGE_PIN M20 [get_ports reset]
set_property PACKAGE_PIN M19 [get_ports wbDataForOutput]
set_property PACKAGE_PIN M18 [get_ports wbDataForInput]

set_property PACKAGE_PIN B19 [get_ports wbWriteOut]

set_property PACKAGE_PIN B20 [get_ports {wbInputData[9]}]
